from pathlib import Path


PROJECT_DIRECTORY = Path(__file__).resolve().parent

CAMERA_INDEX = 0
MIRROR_CAMERA_IMAGE = True
MAXIMUM_FACE_COUNT = 2

MODEL_PATH = PROJECT_DIRECTORY / "models" / "face_landmarker.task"
OUTPUT_DIRECTORY = PROJECT_DIRECTORY / "outputs"
FFT_SAMPLE_DIRECTORY = PROJECT_DIRECTORY / "fft_samples"

# Goruntu kalitesi esikleri
MINIMUM_FACE_AREA_RATIO = 0.08
MINIMUM_BLUR_SCORE = 80.0
MINIMUM_BRIGHTNESS = 60.0
MAXIMUM_BRIGHTNESS = 200.0

# Kafa ve agiz hizalama esikleri
MAXIMUM_YAW_DEGREES = 15.0
MAXIMUM_PITCH_DEGREES = 12.0
MAXIMUM_ROLL_DEGREES = 10.0
MAXIMUM_MOUTH_ANGLE_DEGREES = 10.0
MAXIMUM_MOUTH_LATERAL_DIFFERENCE = 0.25
MAXIMUM_JAW_OPEN_SCORE = 0.35

# Deneysel Moire / periyodik desen pre-control ayarlari.
# Bunlar evrensel esikler degildir. Gercek kamera, ekran, baski, mesafe ve isik
# verileriyle kalibre edilmelidir; baslangic davranisi bilerek konservatiftir.
EXPERIMENTAL_MOIRE_INNER_RADIUS = 0.14
EXPERIMENTAL_MOIRE_OUTER_RADIUS = 0.82
EXPERIMENTAL_MOIRE_BACKGROUND_SIGMA = 4.0
EXPERIMENTAL_MOIRE_LOCAL_MAXIMUM_SIZE = 5
EXPERIMENTAL_MOIRE_PEAK_MINIMUM_DISTANCE = 5
EXPERIMENTAL_MOIRE_LOCAL_CONTRAST_SIZE = 9
EXPERIMENTAL_MOIRE_MINIMUM_PEAK_Z_SCORE = 6.5
EXPERIMENTAL_MOIRE_MINIMUM_CONTRAST_Z_SCORE = 4.0
EXPERIMENTAL_MOIRE_MINIMUM_PEAK_ENERGY_SHARE = 0.0002
EXPERIMENTAL_MOIRE_MAXIMUM_PEAK_COUNT = 24
EXPERIMENTAL_MOIRE_PEAK_PATCH_RADIUS = 2
EXPERIMENTAL_MOIRE_STRONG_PEAK_Z_SCORE = 11.0
EXPERIMENTAL_MOIRE_TARGET_PEAK_COUNT = 8
EXPERIMENTAL_MOIRE_ENERGY_CONCENTRATION_START = 0.002
EXPERIMENTAL_MOIRE_ENERGY_CONCENTRATION_FULL = 0.04
EXPERIMENTAL_MOIRE_SYMMETRY_TOLERANCE_PIXELS = 3.0
EXPERIMENTAL_MOIRE_MINIMUM_SYMMETRY_AMPLITUDE_RATIO = 0.35
EXPERIMENTAL_MOIRE_DIRECTION_BIN_COUNT = 12
EXPERIMENTAL_MOIRE_DIRECTION_SHARE_START = 0.35
EXPERIMENTAL_MOIRE_DIRECTION_SHARE_FULL = 0.75

EXPERIMENTAL_MOIRE_PERIODIC_WEIGHT = 0.60
EXPERIMENTAL_MOIRE_SYMMETRY_WEIGHT = 0.22
EXPERIMENTAL_MOIRE_DIRECTION_WEIGHT = 0.18
EXPERIMENTAL_MOIRE_SUSPICIOUS_SCORE = 72.0
EXPERIMENTAL_MOIRE_SCREEN_REPLAY_SCORE = 86.0
EXPERIMENTAL_MOIRE_RELEASE_SCORE = 52.0
EXPERIMENTAL_MOIRE_HISTORY_SIZE = 10
EXPERIMENTAL_MOIRE_MINIMUM_HISTORY = 6
EXPERIMENTAL_MOIRE_REQUIRED_SUSPICIOUS_FRAMES = 4
EXPERIMENTAL_MOIRE_REQUIRED_RELEASE_FRAMES = 4
EXPERIMENTAL_MOIRE_INVALID_RESET_FRAMES = 4
EXPERIMENTAL_MOIRE_REGION_IOU_RESET_THRESHOLD = 0.45
