from pathlib import Path


PROJECT_DIRECTORY = Path(__file__).resolve().parent

CAMERA_INDEX = 0
MIRROR_CAMERA_IMAGE = True
MAXIMUM_FACE_COUNT = 2

MODEL_PATH = PROJECT_DIRECTORY / "models" / "face_landmarker.task"
OUTPUT_DIRECTORY = PROJECT_DIRECTORY / "outputs"

# Goruntu kalitesi esikleri
MINIMUM_FACE_AREA_RATIO = 0.08
MINIMUM_BLUR_SCORE = 80.0
MINIMUM_BRIGHTNESS = 60.0
MAXIMUM_BRIGHTNESS = 200.0

# Kafa ve agiz hizalama esikleri
MAXIMUM_YAW_DEGREES = 15.0
MAXIMUM_PITCH_DEGREES = 12.0
MAXIMUM_ROLL_DEGREES = 10.0
MAXIMUM_MOUTH_ANGLE_DEGREES = 10.0
MAXIMUM_MOUTH_LATERAL_DIFFERENCE = 0.25
MAXIMUM_JAW_OPEN_SCORE = 0.35
